---
# Replace the fields below with relevant information.
# See https://www.mkdocs.org/user-guide/configuration/
# to learn more about the configuration options.
site_name: AWX Operator Helm Chart
site_url: https://ansible.readthedocs.io/PROJECTNAME
repo_url: https://github.com/ansible-community/awx-operator-helm
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: 'ansible'

nav:
  - Home: 'index.md'
  - 'License': 'license.md'
  - 'helm-install-on-existing-cluster.md'
